doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                schema_filter: '~^(?!messenger_messages|cache_items)~'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
#                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        WEEK: DoctrineExtensions\Query\Mysql\Week
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                hydrators:
                    App\Doctrine\Hydrators\ColumnHydrator: App\Doctrine\Hydrators\ColumnHydrator
                    App\Doctrine\Hydrators\DomesticSurveyExportHydrator: App\Doctrine\Hydrators\DomesticSurveyExportHydrator

            audit_log:
#                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    AuditLog:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/AuditLog'
                        prefix: 'App\Entity\AuditLog'
                        alias: AuditLog
