# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: null
#        cookie_secure: auto
#        cookie_samesite: lax

        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        storage_factory_id: session.storage.factory.native

        cookie_secure: true
        cookie_samesite: lax

        ## Pentest recommended limiting session lifetim
        # using gc_maxlifetime looks at idle time, not just a finite cookie lifetime
        gc_maxlifetime: 3600
        gc_probability: 5
        gc_divisor: 100

    #esi: true
    #fragments: true
    php_errors:
        log: true
