twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'theme.html.twig'

    globals:
        admin_hostname: '%admin_hostname%'
        csp_inline_script_helper: '@App\Utility\CspInlineScriptHelper'
        env_label_admin: '%env_label_admin%'
        env_label_background: '%env_label_background%'
        env_label_colour: '%env_label_colour%'
        env_label_frontend: '%env_label_frontend%'
        frontend_hostname: '%frontend_hostname%'
