## GCP AppEngine config
runtime: php74
entrypoint: serve public/index.php

default_expiration: "5s"

handlers:
  - url: /build
    static_dir: public/build
    http_headers:
      Cache-Control: private
  - url: /.*
    script: auto

skip_files:
  - node_modules/

inbound_services:
  - warmup