steps:
    # Install dependencies
    - name: node
      entrypoint: yarn
      args: ['install', '--frozen-lockfile']
    # Run custom commands
    - name: node
      entrypoint: yarn
      args: ['run', 'deploy-build']
    # deploy
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy", "app.default.yaml"]
      env:
        - 'DATABASE_URL=mysql://root:nJng0ydueBDPcO6N@localhost?unix_socket=/cloudsql/dft-sres-rfs-test:europe-west1:dft-sres-rfs-test;dbname=dft_rfs_test'
        - 'ADMIN_USERS_PASSWORD_FILE=%kernel.project_dir%/admin-passwords'
        - 'FRONTEND_HOSTNAME=dft-sres-rfs-test.ew.r.appspot.com'
        - 'ADMIN_HOSTNAME=admin-dot-dft-sres-rfs-test.ew.r.appspot.com'
    # deploy
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy", "app.admin.yaml"]
      env:
        - 'DATABASE_URL=mysql://root:nJng0ydueBDPcO6N@localhost?unix_socket=/cloudsql/dft-sres-rfs-test:europe-west1:dft-sres-rfs-test;dbname=dft_rfs_test'
        - 'ADMIN_USERS_PASSWORD_FILE=%kernel.project_dir%/admin-passwords'
        - 'FRONTEND_HOSTNAME=dft-sres-rfs-test.ew.r.appspot.com'
        - 'ADMIN_HOSTNAME=admin-dot-dft-sres-rfs-test.ew.r.appspot.com'

timeout: "900s"
