steps:
    # Install dependencies
    - name: node
      id: 'node-install'
      entrypoint: yarn
      args: ['install', '--frozen-lockfile']
    # Run custom commands
    - name: node
      id: 'node-build'
      entrypoint: yarn
      args: ['run', 'deploy-build']
      waitFor: ['node-install']

    # copy project relevant app deploy files
    - name: 'alpine'
      id: 'copy-deploy-files'
      args: ['cp', 'config/gcloud-build/$PROJECT_ID/*', '.']
      waitFor: ['-']

    # deploy
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy", "app.default.yaml"]
      waitFor: ['node-build', 'copy-deploy-files']
    # deploy
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy", "app.admin.yaml"]
      waitFor: ['node-build', 'copy-deploy-files']

timeout: "900s"
