steps:
    # Install dependencies
    - name: node
      id: 'node-install'
      entrypoint: yarn
      args: ['install', '--frozen-lockfile']
    # Run custom commands
    - name: node
      id: 'node-build'
      entrypoint: yarn
      args: ['run', 'deploy-build']
      waitFor: ['node-install']

    # copy common app deploy files
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
      id: 'copy-common-deploy-files'
      args: ['gsutil', 'rsync', 'config/gcloud-build/all/', '.']
      waitFor: ['-']
    # copy project specific app deploy files
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
      id: 'copy-project-deploy-files'
      args: ['gsutil', 'rsync', 'config/gcloud-build/$PROJECT_ID/', '.']
      waitFor: ['copy-common-deploy-files']

    # deploy default service
    - name: "gcr.io/cloud-builders/gcloud"
      id: 'deploy-default-service'
      args: ["app", "deploy", "app.default.yaml"]
      waitFor: ['node-build', 'copy-project-deploy-files']
    # deploy admin service
    - name: "gcr.io/cloud-builders/gcloud"
      id: 'deploy-admin-service'
      args: ["app", "deploy", "app.admin.yaml"]
      waitFor: ['node-build', 'copy-project-deploy-files']

## https://stackoverflow.com/questions/58893845/cloud-build-permission-denied-when-deploy-to-cloud-run-with-set-sql-instance
# the cloud build service account needs iam.serviceAccountUser role to perform this - but we don't have permission to add that role!
#    # deploy cron jobs
#    - name: "gcr.io/cloud-builders/gcloud"
#      args: ["app", "deploy", "cron.yaml"]
#      waitFor: ['deploy-default-service', 'deploy-admin-service']

timeout: "900s"
