options:
    env:
        - 'APP_SECRET=${_APP_SECRET}'
        - 'FRONTEND_HOSTNAME=${_FRONTEND_HOSTNAME}'

steps:
    # Start by running some pre-install actions
    - name: node:20
      id: 'pre-install-script'
      entrypoint: sh
      args: ['-c', 'config/gcloud-build/call-remote-action.sh -a pre-install']
      waitFor: ['-']

    # Copy depoyment config files in to root directory (alpine required for gsutil)
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
      id: 'copy-deploy-files'
      entrypoint: sh
      args: ['-c', 'gsutil rsync config/gcloud-build/all/ . && gsutil rsync config/gcloud-build/$PROJECT_ID/ .']
      waitFor: ['pre-install-script']

    # We need vendor/ghost/govuk-frontend-bundle since the CSS/JS references resources from it
    - name: composer:2.3
      id: 'install-ghost-bundle'
      entrypoint: sh
      args: ['-c', 'composer install -vvv --ignore-platform-reqs --no-scripts']
      waitFor: ['copy-deploy-files']

    # build assets, and .env.local file
    - name: node:20
      id: 'yarn-build'
      entrypoint: sh
      args: ['-c', 'yarn install --frozen-lockfile --network-timeout 60000 && yarn run deploy-build && yarn run build-env-subs']
      env:
          - 'APP_ENV=prod'
          - 'ADMIN_HOSTNAME=${_ADMIN_HOSTNAME}'
          - 'DATABASE_URL=${_DATABASE_URL}'
          - 'ALPHAGOV_NOTIFY_API_KEY=${_ALPHAGOV_NOTIFY_API_KEY}'
          - 'APP_FEATURES=${_APP_FEATURES}'
          - 'GOOGLE_BUCKET_EXPORT=${_GOOGLE_BUCKET_EXPORT}'
          - 'APP_DISABLE_REMINDERS=${_APP_DISABLE_REMINDERS}'
          - 'APP_ENV_LABEL_ADMIN=${_APP_ENV_LABEL_ADMIN}'
          - 'APP_ENV_LABEL_FRONTEND=${_APP_ENV_LABEL_FRONTEND}'
          - 'APP_ENV_LABEL_COLOUR="${_APP_ENV_LABEL_COLOUR}"'
          - 'APP_ENV_LABEL_BACKGROUND="${_APP_ENV_LABEL_BACKGROUND}"'

      waitFor: ['install-ghost-bundle']

    ## The app deployment will not run `composer install` if the composer.lock file has not changed
    ## meaning that post install scripts, or even update scripts to not get run
    # deploy default service
    - name: "gcr.io/cloud-builders/gcloud"
      id: 'deploy-default-service'
      args: ["app", "deploy", "app.default.yaml", "--ignore-file=.gcloudignore", "--no-cache"]
      waitFor: ['yarn-build']
    # deploy admin service
    - name: "gcr.io/cloud-builders/gcloud"
      id: 'deploy-admin-service'
      args: ["app", "deploy", "app.admin.yaml", "--ignore-file=.gcloudignore", "--no-cache"]
      waitFor: ['deploy-default-service']


    # Finish up by calling the post-install-script
    - name: node:20
      id: 'post-install-script'
      entrypoint: sh
      args: ['-c', 'config/gcloud-build/call-remote-action.sh -a post-install']
      waitFor: ['deploy-default-service', 'deploy-admin-service']


    ## https://stackoverflow.com/questions/58893845/cloud-build-permission-denied-when-deploy-to-cloud-run-with-set-sql-instance
    # the cloud build service account needs iam.serviceAccountUser role to perform this - but we don't have permission to add that role!
    # deploy cron jobs
    - name: "gcr.io/cloud-builders/gcloud"
      id: 'deploy-cron'
      args: ["app", "deploy", "cron.yaml"]
      waitFor: ['deploy-default-service', 'deploy-admin-service']

timeout: "1800s"
