front_end:
    # The glob (`**/*`) is needed for the `exclude` directive to work
    resource: '../../src/Controller/**/*'
    exclude:
        - '../../src/Controller/Cron/'
        - '../../src/Controller/Admin/'
        - '../../src/Controller/Workflow/'
    type: annotation
    host: '%frontend_hostname%'

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    host: '%admin_hostname%'

cron:
    resource: ../../src/Controller/Cron/
    type: annotation
    prefix: /cron
    name_prefix: 'cron_'
    condition: "(request.headers.get('X-Appengine-Cron') === 'true') or (request.headers.get('X-Cloudscheduler') === 'true')"

kernel:
    resource: ../../src/Kernel.php
    type: annotation
