dispatch:
    # Default service serves the typical web resources and all static resources.
    - url: "roadhaulagesurveys.dft.gov.uk/"
      service: default

    # Default service serves simple hostname request.
    - url: "admin.roadhaulagesurveys.dft.gov.uk/"
      service: admin
