cron:
- description: "Messenger consumer"
  url: "/cron/messenger/consume"
  schedule: 'every 5 minutes synchronized'
- description: "Reminder processor"
  url: "/cron/reminders/process"
  schedule: "every day 06:00"
  timezone: "Europe/London"
- description: "Create RoRo surveys"
  url: "/cron/roro/create-surveys"
  schedule: "1 of month 01:00"
  timezone: "Europe/London"
- description: "Personal data cleanup processor"
  url: "/cron/cleanup/personal-data"
  schedule: "2nd sunday of month 05:00"
  timezone: "Europe/London"
- description: "Survey cleanup processor"
  url: "/cron/cleanup/surveys"
  schedule: "2nd sunday of month 01:00"
  timezone: "Europe/London"
