## GCP AppEngine config
runtime: php74
entrypoint: serve public/index.php
service: default
env_variables:
  APP_ENV: "prod"
  DATABASE_URL: "mysql://root:nJng0ydueBDPcO6N@localhost?unix_socket=/cloudsql/dft-sres-rfs-test:europe-west1:dft-sres-rfs-test;dbname=dft_rfs_test"
  ADMIN_USERS_PASSWORD_FILE: "%kernel.project_dir%/admin-passwords"
  FRONTEND_HOSTNAME: "dft-sres-rfs-test.ew.r.appspot.com"
  ADMIN_HOSTNAME: "admin-dot-dft-sres-rfs-test.ew.r.appspot.com"

default_expiration: "5s"

handlers:
  - url: /build
    static_dir: public/build
  - url: /.*
    script: auto

inbound_services:
  - warmup
