monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        form_validation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.form_validation.log"
            level: debug
            channels: [formValidation]

# [START add_stackdriver_to_symfony_monolog]
        google_cloud:
            type: service
            id: monolog_psr_batch_logger

services:
    # Monolog wrapper
    monolog_psr_batch_logger:
        class: Monolog\Handler\PsrHandler
        arguments: ['@google_cloud_stackdriver_psr_batch_logger']

    # PsrBatchLogger
    google_cloud_stackdriver_psr_batch_logger:
        class: Google\Cloud\Logging\PsrLogger
        factory: ['Google\Cloud\Logging\LoggingClient', 'psrBatchLogger']
        arguments: ['app']
# [END add_stackdriver_to_symfony_monolog]