<?php

namespace App\ML\FileType;

class CsrgtFileType implements FileTypeInterface
{
    #[\Override]
    public function getColumnsNames(): array
    {
        return [
            'SurveyStartDate',
            'BusinessType',
            'BusinessType_NACE2',   # This is generated by DfT
            'JourneyType',
            'TypeOfGoods',          # Textual description of the goods
            'TypeOfGoods_NST2007',  # NST2007 code - target field
            'TypeOfGoods_Std',      # Textual representation of the NST2007 code
            'MOA_Std',
            'DangerousGoods',
            'WeightOfGoodsCarriedKG',
            'WeightOfGoodsDelivered',
            'WeightOfGoodsCollected',
            'LoadedKMfinal',
            'EmptyKMfinal',
            'NumberOfStopsForDelivery',
            'NumberOfStopsForCollection',
            'NumberOfStopsForBoth',
        ];
    }

    #[\Override]
    public function getName(): string
    {
        return 'csrgt';
    }
}