<?php

namespace App\ML;

class Nst2007
{
    protected array $mapping = [
        "1" => "Products of agriculture, hunting, and forestry; fish and other fishing products",
        "1.1" => "Cereals",
        "1.2" => "Potatoes",
        "1.3" => "Sugar beet", 
        "1.4" => "Other fresh fruit and vegetables",
        "1.5" => "Products of forestry and logging",
        "1.6" => "Live plants and flowers",
        "1.7" => "Other substances of vegetable origin",
        "1.8" => "Live animals",
        "1.9" => "Raw milk from bovine cattle",
        "1.A" => "Other raw materials of animal origin",
        "1.B" => "Fish and other fishing products",
        "2" => "Coal and lignite; crude petroleum and natural gas",
        "2.1" => "Coal and lignite", 
        "2.2" => "Crude petroleum", 
        "2.3" => "Natural gas", 
        "3" => "Metal ores and other mining and quarrying products; peat; uranium and thorium",
        "3.1" => "Iron ores",
        "3.2" => "Non ferrous metal ores (except uranium and thorium ores)",
        "3.3" => "Chemical and (natural) fertilizer minerals",
        "3.4" => "Salt",
        "3.5" => "Stone",
        "3.6" => "Uranium and thorium ores",
        "4" => "Food products",
        "4.1" => "Meat",
        "4.2" => "Fish and fish products",
        "4.3" => "Fruit and vegetables",
        "4.4" => "Animal and vegetable oils and fats",
        "4.5" => "Dairy products and ice cream",
        "4.6" => "Grain mill products",
        "4.7" => "Beverages",
        "4.8" => "Other food products n.e.c. and tobacco products (except in parcel service or grouped)",
        "4.9" => "Various food products and tobacco products in parcel service or grouped",
        "5" => "Textiles and textile products; leather and leather products",
        "5.1" => "Textiles", 
        "5.2" => "Wearing apparel and articles of fur",
        "5.3" => "Leather and leather products", 
        "6" => "Wood and products of wood and cork (except furniture); articles of straw and plaiting materials; pulp, paper and paper products; printed matter and recorded media",
        "6.1" => "Products of wood and cork (except furniture)",
        "6.2" => "Pulp",
        "6.3" => "Printed matter and recorded media",
        "7" => "Coke and refined petroleum products", 
        "7.1" => "Coke oven products; briquettes, ovoids and similar solid fuels",
        "7.2" => "Liquid refined petroleum products", 
        "7.3" => "Gaseous",
        "7.4" => "Solid or waxy refined petroleum products",
        "8" => "Chemicals, chemical products, and man-made fibers; rubber and plastic products ; nuclear fuel",
        "8.1" => "Basic mineral chemical products",
        "8.2" => "Basic organic chemical products",
        "8.3" => "Nitrogen compounds and fertilizers (except natural fertilizers)",
        "8.4" => "Basic plastics and synthetic rubber in primary forms",
        "8.5" => "Pharmaceuticals and parachemicals including pesticides and other agro-chemical products", 
        "8.6" => "Rubber or plastic products",
        "8.7" => "Nuclear fuel",
        "9" => "Other non metallic mineral products",
        "9.1" => "Glass and glass products",
        "9.2" => "Cement",
        "9.3" => "Other construction materials",
        "10" => "Basic metals; fabricated metal products, except machinery and equipment",
        "10.1" => "Basic iron and steel and ferro-alloys and products of the first processing of iron and steel (except tubes)",
        "10.2" => "Non ferrous metals and products thereof",
        "10.3" => "Tubes",
        "10.4" => "Structural metal products",
        "10.5" => "Boilers, hardware, weapons and other fabricated metal products",
        "11" => "Machinery and equipment n.e.c.; office machinery and computers; electrical machinery and apparatus n.e.c.; radio, television and communication equipment and apparatus; medical, precision and optical instruments; watches and clocks",
        "11.1" => "Agricultural and forestry machinery",
        "11.2" => "Domestic appliances n.e.c. (White goods)",
        "11.3" => "Office machinery and computers",
        "11.4" => "Electric machinery and apparatus n.e.c.",
        "11.5" => "Electronic components and emission and transmission appliances",
        "11.6" => "Television and radio receivers; sound or video recording or reproducing apparatus and associated goods (Brown goods)",
        "11.7" => "Medical",
        "11.8" => "Other machines",
        "12" => "Transport equipment", 
        "12.1" => "Automobile industry products",
        "12.2" => "Other transport equipment",
        "13" => "Furniture; other manufactured goods n.e.c.",
        "13.1" => "Furniture", 
        "13.2" => "Other manufactured goods",
        "14" => "Secondary raw materials; municipal wastes and other wastes", 
        "14.1" => "Household and municipal waste",
        "14.2" => "Other waste and secondary raw materials",
        "15" => "Mail",
        "15.1" => "Mail",
        "15.2" => "Parcels",
        "16" => "Equipment and material utilized in the transport of goods", 
        "16.1" => "Containers and swap bodies in service",
        "16.2" => "Pallets and other packaging in service",
        "17" => "Goods moved in the course of household and office removals; baggage and articles accompanying travellers; motor vehicles being moved for repair; other non market goods n.e.c.", 
        "17.1" => "Household removal",
        "17.2" => "Baggage and articles accompanying travellers",
        "17.3" => "Vehicles for repair",
        "17.4" => "Plant equipment",
        "17.5" => "Other non market goods n.e.c.",
        "18" => "Grouped goods",
        "19" => "Unidentifiable goods: goods which for any reason cannot be identified and therefore cannot be assigned to groups 01-16.",
        "19.1" => "Unidentifiable goods in containers or swap bodies",
        "19.2" => "Other unidentifiable goods",
        "20" => "Other goods not elsewhere classified",        
    ];

    public function getDescription(string $code): ?string
    {
        if (str_ends_with($code, '.0')) {
            $code = substr($code, 0, -2);
        }
        return $this->mapping[$code] ?? null;
    }
}